version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- dotnet restore src
build_script:
- dotnet build src /nologo
- dotnet pack src --no-build /nologo
test_script:
- ps: src\test.ps1 -All
artifacts:
- path: 'bin\Nerdbank.MSBuildExtension\Release\*.nupkg'
  name: NuGet Package
