version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- msbuild /nologo /v:quiet /m src\Nerdbank.MSBuildExtension.sln /t:restore
build_script:
- msbuild /nologo /v:minimal /m src\Nerdbank.MSBuildExtension.sln /t:build,pack
test_script:
- ps: src\test.ps1
artifacts:
- path: 'bin\Nerdbank.MSBuildExtension\Release\*.nupkg'
  name: NuGet Package
